name: "Nix Omnix CI"
env:
  CACHIX_AUTH_KEY: ${{ secrets.CACHIX_AUTH_TOKEN }}

on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hyprflake.cachix.org-1:7fpoBMQuosbaoqxQ5bsxR2GPVQ3mjBp7dfziXc4e+hM=
            substituters = https://cache.nixos.org/ https://hyprflake.cachix.org
      - run: just fmt
      - run: "nix profile install github:juspay/omnix nixpkgs#cachix"
      - run: 'om ci | cachix push hyprflake'
