name: "Nix Omnix CI (with nixbuild)"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: nixbuild/nixbuild-action@v19
        with:
            nixbuild_token: ${{ secrets.NIXBUILD_KEY }}
            generate_summary_for: "job"
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install Cachix and Omnix
        run: "nix profile install --accept-flake-config github:juspay/omnix nixpkgs#cachix"
      - name: Authenticate Cachix
        run: "cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build all flake outputs and push to Cachix
        run: "om ci | cachix push hyprflake"
