name: "Nix Omnix CI (with nixbuild)"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "${{ secrets.SSH_KEY }}" > ssh_key
            ssh -o StrictHostKeyChecking=no -i ./ssh_key root@icedancer.viiol.xyz echo hi
        name: "Add ssh-key"
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf:

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install Cachix and Omnix
        run: "nix profile install --accept-flake-config github:juspay/omnix nixpkgs#cachix"
      - name: Authenticate Cachix
        run: "cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build all flake outputs and push to Cachix
        run: "om ci | cachix push hyprflake"
