name: "Nix Omnix CI (with nixbuild)"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - run: |
            echo "${{ secrets.SSH_KEY }}" > ssh_key
            chmod 0700 ./ssh_key
            # ssh -o StrictHostKeyChecking=no -i ./ssh_key root@icedancer.viiol.xyz echo hi
        name: "Add ssh-key"
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
          extra-conf: |
            builders-use-substitutes = true
            require-sigs = false
            builder = ssh://vii@eu.nixbuild.net x86_64-linux /Users/vii/.ssh/id_ed25519 100 1 benchmark,big-parallel
            substituters = https://cache.nixos.org/ https://hyprflake.cachix.org/ ssh://eu.nixbuild.net
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hyprflake.cachix.org-1:7fpoBMQuosbaoqxQ5bsxR2GPVQ3mjBp7dfziXc4e+hM= nixbuild.net/bob-1:8tJU22/XxyINhP+wM65gwSIlg0rrQrmWhFf5+8u8F/s=
            trusted-users = vii root

                

      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install Cachix and Omnix
        run: "nix profile install --accept-flake-config github:juspay/omnix nixpkgs#cachix"
      - name: Authenticate Cachix
        run: "cachix authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build all flake outputs and push to Cachix
        run: "om ci | cachix push hyprflake"
